name: Remove Expired Workflow Runs
on:
  schedule: [{ cron: "47 5 * * *" }] # Schedule to run the workflow every day at 5:30 AM
  workflow_dispatch:

jobs:
  clean:
    name: Delete Expired Workflow Runs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action Code
        uses: actions/checkout@v2

      - name: Run Delete Script
        # run: sh ./delete.sh (your org or github name) (your repo name)
        run: sh ./delete.sh gigamaster gigamaster
        working-directory: .github/actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
