# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "27 5 * * *" }] # Schedule to run the workflow every day at 5:30 AM
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          # Options
          template: classic
          config_timezone: Europe/Paris 
          filename: github-metrics.svg  
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity
          plugin_achievements: yes
          plugin_achievements_only: >-
           polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
           scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact 
          plugin_achievements_threshold: X
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
